# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "s1" do |s1|
    s1.vm.network "private_network", ip: "172.16.10.10", virtualbox__intnet: "s1"
    s1.vm.network "private_network", ip: "192.168.11.20", virtualbox__intnet: false
    s1.vm.hostname = "s1"
  end

  config.vm.define "s2" do |s2|
    s2.vm.network "private_network", ip: "172.16.20.20", virtualbox__intnet: "s2"
    s2.vm.network "private_network", ip: "192.168.11.21", virtualbox__intnet: false
    s2.vm.hostname = "s2"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

end
