---
- hosts: all
  become: yes
  tasks:
  - name: set timezone
    command: ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime

  - name: install epel-release
    yum: name=epel-release state=latest

  - name: install packages
    yum: name={{ item }} state=present
    with_items:
      - openvpn
      - traceroute
      - vim
      - wget
      - unzip
      - tcpdump
      - iperf3

  - name: copy secret
    copy: src=ptp.key dest=/etc/openvpn/keys/ owner=root group=root mode=0600

  - name: copy openvpn configuration file
    copy: src={{ inventory_hostname }}.conf.j2 dest=/etc/openvpn/server.conf owner=root group=root mode=0644

  - name: openvpn start
    service: name=openvpn@server state=started enabled=yes

